language: rust
cache: cargo
sudo: false

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

jobs:
  include:
    - stage: builds
      rust: stable
      script: ./scripts/travis/build.sh
    - rust: beta
      script: ./scripts/travis/build.sh
    - rust: nightly
      script: ./scripts/travis/build.sh

    - stage: tests
      rust: stable
      script: ./scripts/travis/test.sh
    - rust: beta
      script: ./scripts/travis/test.sh
    - rust: nightly
      script: ./scripts/travis/test.sh

    - stage: deployments
      rust: stable
      install: skip
      script: skip
      deploy:
        provider: cargo
        token: "${CRATES_TOKEN}"
        on:
          branch: testing/version_check
          tags: true
