parsing:
  map-file: 'resources/maps/bidirectional-bait.fmi'
  vehicles:
    category: 'Car'
    are-drivers-picky: false
  nodes:
  - meta: { info: 'NodeId', id: 'node-id' }
  - metric: { unit: 'Latitude', id: 'latitude' }
  - metric: { unit: 'Longitude', id: 'longitude' }
  edges:
  - meta: { info: 'SrcId', id: 'src-id' }
  - meta: { info: 'DstId', id: 'dst-id' }
  - metric: { unit: 'Meters', id: 'meters' }
  - metric: { unit: 'KilometersPerHour', id: 'kmph' }
  generating:
    nodes: []
    edges:
    - convert:
        from: { unit: 'Meters', id: 'meters' }
        to: { unit: 'Kilometers', id: 'kilometers' }
    - calc:
        result: { unit: 'Minutes', id: 'minutes' }
        a: { unit: 'Kilometers', id: 'kilometers' }
        b: { unit: 'KilometersPerHour', id: 'kmph' }
