parsing:
  map-file: 'resources/maps/isle-of-man_2020-03-14.osm.pbf'
  vehicles:
    category: 'Car'
    are-drivers-picky: false
  nodes:
  - meta: { info: 'NodeId', id: 'node-id' }
  - metric: { unit: 'Latitude', id: 'latitude' }
  - metric: { unit: 'Longitude', id: 'longitude' }
  edges:
  - meta: { info: 'SrcId', id: 'src-id' }
  - meta: { info: 'DstId', id: 'dst-id' }
  - ignored # shouldn't matter, so add it here to test this
  - metric: { unit: 'KilometersPerHour', id: 'kmph' }
  - metric: { unit: 'LaneCount', id: 'lanecount' }
  generating:
    nodes:
    - meta: { info: 'NodeIdx', id: 'node-idx' }
    edges:
    - meta: { info: 'SrcIdx', id: 'src-idx' }
    - meta: { info: 'DstIdx', id: 'dst-idx' }
    - meta: { info: 'ShortcutIdx0', id: 'sc-idx-0' }
    - meta: { info: 'ShortcutIdx1', id: 'sc-idx-1' }
    - haversine: { unit: 'Kilometers', id: 'km' }
    - calc:
        result: { unit: 'Minutes', id: 'min' }
        a: { unit: 'Kilometers', id: 'km' }
        b: { unit: 'KilometersPerHour', id: 'kmph' }
