parser:
  map-file: 'resources/maps/isle-of-man_2019-09-05.osm.pbf'
  vehicles:
    category: 'Car'
    are-drivers-picky: false
  nodes:
  - category: 'NodeId'
  - category: 'Latitude'
  - category: 'Longitude'
  edges:
  - category: 'SrcId'
  - category: 'DstId'
  - category: 'Meters'
    is-provided: false
  - category: 'KilometersPerHour'
  - category: 'Seconds'
    is-provided: false
    calc-rules: ['Meters', 'KilometersPerHour']

generator:
  map-file: 'resources/maps/isle-of-man_2019-09-05.fmi'
  nodes:
  - category: 'NodeId'
  - category: 'NodeId'
  - category: 'Latitude'
  - category: 'Longitude'
  - category: 'Ignore' # height
  - category: 'Level'
  edges:
  - id: 'SrcId'
  - id: 'DstId'
  - id: 'Meters'
  - id: 'KilometersPerHour'
  - id: 'Seconds'
