parsing:
  map-file: 'resources/maps/isle-of-man_2020-03-14.osm.pbf'
  vehicles:
    category: 'Car'
    are-drivers-picky: false
  nodes:
  - meta: { info: 'NodeId', id: 'node-id' }
  - metric: { unit: 'Latitude', id: 'latitude' }
  - metric: { unit: 'Longitude', id: 'longitude' }
  edges:
  - meta: { info: 'SrcId', id: 'src-id' }
  - meta: { info: 'DstId', id: 'dst-id' }
  - metric: { unit: 'KilometersPerHour', id: 'kmph' }
  generating:
    nodes:
    edges:
    - meta: { info: 'SrcIdx', id: 'src-idx' }
    - meta: { info: 'DstIdx', id: 'dst-idx' }
    - meta: { info: 'ShortcutIdx0', id: 'sc-idx-0' }
    - meta: { info: 'ShortcutIdx1', id: 'sc-idx-1' }
    - haversine: { unit: 'Kilometers', id: 'km' }
    - calc:
        result: { unit: 'Minutes', id: 'min' }
        a: { unit: 'Kilometers', id: 'km' }
        b: { unit: 'KilometersPerHour', id: 'kmph' }

writing:
  map-file: 'resources/maps/isle-of-man_2020-03-14.fmi'
  nodes:
  - id: 'node-idx'
  - id: 'node-id'
  - id: 'latitude'
  - id: 'longitude'
  - ignored # height
  - ignored # level for contraction-hierarchies
  edges:
  - id: 'src-idx'
  - id: 'dst-idx'
  - id: 'km'
  # - id: 'kmph' # nope because addition (in ch) makes no sense
  - id: 'seconds'
  - id: 'sc-idx-0'
  - id: 'sc-idx-1'
