graph:
  # relative to user, not to script
  map-file: 'relative-path-to-map-file'

  vehicles:
    category: 'Car' # | 'Bicycle' | 'Pedestrian'
    # Value `false` leads to more edges,
    # because edges are added, which are okay,
    # but not suitable for this vehicle-category.
    are-drivers-picky: false

  edges:
    # Here, the order matters, if the map-file has a metric-order, like
    # `fmi`-files. Each metric below will be stored in the graph. Metrics below,
    # which have `provided=false`, will be calculated by other metrics and the
    # result is being stored.
    #
    # Default-Ids are the category-name, hence calc-rules are using
    # category-names, which are actually ids.
    #
    # In module 'defaults', set the inline-size accordingly for best performance
    # and memory-usage.
    metrics:

    - category: 'Id'
      id: 'src-id'

    - category: 'Id'
      id: 'dst-id'

    - category: 'Meters'
      id: 'to-the-moon-and-back'
      # Value `false` leads to calculate the value via coordinates and haversine.
      is-provided: false

    # categories can be used twice
    - category: 'Meters'
      is-provided: true

    - category: 'KilometersPerHour'
      id: 'faster-than-light'
      # Value `false` leads to calculate the value via length and duration.
      is-provided: true
      calc-rules: ['to-the-moon-and-back', 'Seconds']

    - category: 'Seconds'
      # Value `false` leads to calculate the value via length and maxspeed.
      is-provided: false
      calc-rules: ['to-the-moon-and-back', 'faster-than-light']

    - category: 'LaneCount'
      is-provided: true

    - category: 'Custom'
      id: 'my-custom-value'
      is-provided: true

    - category: 'Ignore'
      id: 'unnecessary'

# The metrics, which should be considered in routing, are listed here.
# The given alphas are used as scale.
#
# Optional, but will panic as soon as routing will try to use it
routing:
- id: 'to-the-moon-and-back',
  # optional; default is 1.0
  alpha: 169.0
- id: 'Seconds',
  # optional; default is 1.0
  alpha: 331.0
