parsing:
  map-file: 'custom/results/isle_of_man_2020-03-14/utc_YYYY-mm-dd_HH-MM-SS/balanced_graph.fmi'
  nodes:
  - ignored # node-idx
  - meta: { info: 'NodeId', id: 'node-id' }
  - metric: { unit: 'Latitude', id: 'latitude' }
  - metric: { unit: 'Longitude', id: 'longitude' }
  edges:
    # already normalized
    will_normalize_metrics_by_mean: false
    data:
    - meta: { info: 'EdgeId', id: 'edge-id' }
    - meta: { info: 'SrcId', id: 'src-id' }
    - meta: { info: 'DstId', id: 'dst-id' }
    - metric: { unit: 'Kilometers', id: 'kilometers' }
    - metric: { unit: 'Hours', id: 'hours' }
    - metric: { unit: 'LaneCount', id: 'lane-count' }
    - metric: { unit: 'F64', id: 'workload' }
    - ignored # dummy
  generating:
    nodes: []
    edges:
      # src-coords
    - meta: { info: 'SrcLat', id: 'src-lat' }
    - meta: { info: 'SrcLon', id: 'src-lon' }
      # dst-coords
    - meta: { info: 'DstLat', id: 'dst-lat' }
    - meta: { info: 'DstLon', id: 'dst-lon' }
routing:
  route-pairs-file: 'custom/results/isle_of_man_2020-03-14/utc_YYYY-mm-dd_HH-MM-SS/evaluation/10_000_eval.route-pairs'
  algorithm: 'Dijkstra'
  metrics:
  - id: 'kilometers'
  - id: 'hours'
    tolerated-scale: 1.4
  - id: 'workload'
evaluating_balance:
  seed: 24
  number_of_threads: 4
  # .../1/stats is needed, e.g. for visualization via python-script
  results-dir: 'custom/results/isle_of_man_2020-03-14/utc_YYYY-mm-dd_HH-MM-SS/evaluation/dijkstra/1/stats'
  monitoring:
    export_vehicles_for_SMARTS: true
    edges-info:
      file: 'edges-info.csv'
      # optional; default is false, meaning
      # if the graph has normalized metrics,
      # it will be printed normalized.
      # If true, metrics will be denormalized before printing.
      will_denormalize_metrics_by_mean: false
      with_shortcuts: false
      ids:
      - id: 'edge-id'
      - id: 'src-lat'
      - id: 'src-lon'
      - id: 'dst-lat'
      - id: 'dst-lon'
      - id: 'kilometers'
      - id: 'lane-count'
