parsing:
  map-file: 'resources/isle_of_man_2020-03-14/graph.fmi'
  vehicles:
    category: 'Car'
    are_drivers_picky: false
  nodes:
  - ignored # node-idx
  - meta: { info: 'NodeId', id: 'node-id' }
  - metric: { unit: 'Latitude', id: 'latitude' }
  - metric: { unit: 'Longitude', id: 'longitude' }
  edges:
    # already normalized
    will_normalize_metrics_by_mean: false
    data:
    - meta: { info: 'SrcId', id: 'src-id' }
    - meta: { info: 'DstId', id: 'dst-id' }
    - metric: { unit: 'Kilometers', id: 'kilometers' }
    - metric: { unit: 'Hours', id: 'hours' }
    - metric: { unit: 'LaneCount', id: 'lane-count' }
  generating:
    nodes: []
    edges:
    - meta: { info: 'EdgeId', id: 'edge-id' }
      # src-coords
    - meta: { info: 'SrcLat', id: 'src-lat' }
    - meta: { info: 'SrcLon', id: 'src-lon' }
      # dst-coords
    - meta: { info: 'DstLat', id: 'dst-lat' }
    - meta: { info: 'DstLon', id: 'dst-lon' }
routing:
  route-pairs-file: 'custom/results/isle_of_man_2020-03-14/evaluation/10_000.route-pairs'
  is_ch-dijkstra: false
  metrics:
  - id: 'kilometers'
  - id: 'hours'
    tolerated-scale: 1.5
evaluating_balance:
  # optional; default is 42
  seed: 42
  number_of_threads: 15
  # .../0/stats is needed for visualization via python-script
  results-dir: 'custom/results/isle_of_man_2020-03-14/evaluation/explorator/0/stats'
  monitoring:
    edges-info:
      file: 'edges-info.csv'
      # optional; default is false, meaning
      # if the graph has normalized metrics,
      # it will be printed normalized.
      # If true, metrics will be denormalized before printing.
      will_denormalize_metrics_by_mean: false
      with_shortcuts: false
      ids:
      - id: 'edge-id'
      - id: 'src-lat'
      - id: 'src-lon'
      - id: 'dst-lat'
      - id: 'dst-lon'
      - id: 'kilometers'
      - id: 'lane-count'
